from app.shared.errores import (
    ErrorConflicto,
    ErrorNoAutenticado,
    ErrorNoEncontrado,
    ErrorPermisoDenegado,
    ErrorValidacion,
)


class DatosInvalidos(ErrorValidacion): ...
class CorreoYaRegistrado(ErrorConflicto): ...
class TransicionCuentaInvalida(ErrorConflicto): ...
class ConflictoConcurrencia(ErrorConflicto): ...
class CredencialesInvalidas(ErrorNoAutenticado): ...
class CuentaInactiva(ErrorNoAutenticado): ...
class UsuarioNoEncontrado(ErrorNoEncontrado): ...
class OperacionNoPermitida(ErrorPermisoDenegado): ...
